# Generated by Django 4.2.11 on 2026-05-18 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('orden', models.PositiveIntegerField(unique=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CampaniaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('orden', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('duracion_dias', models.IntegerField()),
                ('siembra_inicio', models.IntegerField()),
                ('siembra_fin', models.IntegerField()),
                ('no_repetir_sin_intermedio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NivelAntiguedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('orden', models.PositiveIntegerField(unique=True)),
                ('lag', models.IntegerField()),
                ('alfa', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TipoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('es_porcentual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SlotSiembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('orden', models.PositiveIntegerField(unique=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='core.campania')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SetupCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField()),
                ('cultivo_previo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups_como_previo', to='core.cultivo')),
                ('cultivo_siguiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups_como_siguiente', to='core.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='SecuenciaPermitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitido', models.BooleanField(default=True)),
                ('cultivo_previo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias_como_previo', to='core.cultivo')),
                ('cultivo_siguiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias_como_siguiente', to='core.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='RendimientoCultivoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultivo')),
                ('tipo_suelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiposuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('superficie_ha', models.FloatField()),
                ('max_cultivos_principales', models.PositiveIntegerField()),
                ('max_cultivos_secundarios', models.PositiveIntegerField()),
                ('tipo_suelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiposuelo')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactoRotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('cultivo_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impactos_como_actual', to='core.cultivo')),
                ('cultivo_previo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impactos_como_previo', to='core.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialLoteCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('campania_historica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaniahistorica')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultivo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('campania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campania')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultivo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lote')),
                ('tipo_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipocosto')),
            ],
        ),
        migrations.CreateModel(
            name='CompatibilidadCultivoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatible', models.BooleanField(default=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultivo')),
                ('tipo_suelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiposuelo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='setupcultivo',
            constraint=models.UniqueConstraint(fields=('cultivo_previo', 'cultivo_siguiente'), name='unique_setup_cultivo_previo_siguiente'),
        ),
        migrations.AddConstraint(
            model_name='secuenciapermitida',
            constraint=models.UniqueConstraint(fields=('cultivo_previo', 'cultivo_siguiente'), name='unique_secuencia_cultivo_previo_siguiente'),
        ),
        migrations.AddConstraint(
            model_name='rendimientocultivosuelo',
            constraint=models.UniqueConstraint(fields=('cultivo', 'tipo_suelo'), name='unique_rendimiento_cultivo_suelo'),
        ),
        migrations.AddConstraint(
            model_name='impactorotacion',
            constraint=models.UniqueConstraint(fields=('cultivo_previo', 'cultivo_actual'), name='unique_impacto_rotacion_previo_actual'),
        ),
        migrations.AddConstraint(
            model_name='historiallotecultivo',
            constraint=models.UniqueConstraint(fields=('lote', 'cultivo', 'campania_historica'), name='unique_historial_lote_cultivo_campania'),
        ),
        migrations.AddConstraint(
            model_name='costo',
            constraint=models.UniqueConstraint(fields=('cultivo', 'tipo_costo', 'campania', 'lote'), name='unique_costo_cultivo_tipo_campania_lote'),
        ),
        migrations.AddConstraint(
            model_name='compatibilidadcultivosuelo',
            constraint=models.UniqueConstraint(fields=('cultivo', 'tipo_suelo'), name='unique_compatibilidad_cultivo_suelo'),
        ),
    ]
