# Generated by Django 4.2.11 on 2026-05-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('ilu', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutando', 'Ejecutando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionLoteSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_siembra', models.FloatField(blank=True, null=True)),
                ('dia_cosecha', models.FloatField(blank=True, null=True)),
                ('rendimiento', models.FloatField(blank=True, null=True)),
                ('ingreso', models.FloatField(blank=True, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultivo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lote')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.planificacion')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.slotsiembra')),
            ],
        ),
    ]
