# Generated by Django 4.2.11 on 2026-07-21 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


def crear_ambientes_para_lotes_existentes(apps, schema_editor):
    # Backfill: each existing Lote gets one Ambiente mirroring its
    # current tipo_suelo/superficie_ha with a "Medio" expected yield.
    Lote = apps.get_model('core', 'Lote')
    Ambiente = apps.get_model('core', 'Ambiente')
    for lote in Lote.objects.all():
        Ambiente.objects.create(
            lote=lote,
            tipo_suelo=lote.tipo_suelo,
            rendimiento_esperado='M',
            superficie_ha=lote.superficie_ha,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cultivo_habilitado_costo_configurado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimiento_esperado', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=1)),
                ('superficie_ha', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='historiallotecultivo',
            name='rendimiento_kg_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_lote_nombre_ci'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='core.lote'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='tipo_suelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiposuelo'),
        ),
        migrations.AlterUniqueTogether(
            name='ambiente',
            unique_together={('lote', 'tipo_suelo')},
        ),
        migrations.RunPython(
            crear_ambientes_para_lotes_existentes, noop_reverse
        ),
    ]
