# Generated by Django 5.2.17 on 2026-09-04 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_campaniahistorica_anio_inicio_remove_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteSuperficieCultivoCampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_ha', models.FloatField(default=0.0)),
                ('max_ha', models.FloatField(default=0.0)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_superficie', to='core.campania')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_superficie', to='core.cultivo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cultivo', 'campania'), name='unique_limite_cultivo_campania'), models.CheckConstraint(condition=models.Q(('min_ha__gte', 0), ('max_ha__gte', 0), ('min_ha__lte', models.F('max_ha'))), name='chk_limite_superficie_min_lte_max')],
            },
        ),
    ]
